[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cross-Origin-Opener-Policy = "same-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'strict-dynamic' https://fonts.googleapis.com https://www.google.com https://maps.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https: https://formsubmit.co; frame-src 'self' https://www.google.com https://maps.google.com; frame-ancestors 'none'; object-src 'none'; base-uri 'self'; require-trusted-types-for 'script'; trusted-types default;"
    Permissions-Policy = "autoplay=(), camera=(), microphone=(), geolocation=(), interest-cohort=()"
    X-Robots-Tag = "index, follow"
    Content-Language = "ro-RO"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "http://visionedit.ro/*"
  to = "https://visionedit.ro/:splat"
  status = 301
  force = true

# Redirect old Netlify domain to new domain
[[redirects]]
  from = "https://celebrated-lebkuchen-782bc0.netlify.app/*"
  to = "https://visionedit.ro/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://celebrated-lebkuchen-782bc0.netlify.app/*"
  to = "https://visionedit.ro/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"